site_name: Auth Documentation

# Remove for dev
site_url: ""
use_directory_urls: false
# upto here

site_description: >-
  Web3 auth made easy with Arcana Auth. Provide instant, non-custodial wallets in your app.
  Remove the friction of wallet installation, key backup, & crypto on-ramp.

nav: 
  - index.md
  - Introduction: introducing-arcana-auth.md
  - Quick Start: auth-quick-start.md
  - Getting Started:
      - howto/index.md
      - Register App: howto/config_dapp.md
      - Configure Auth: 
        - howto/config_auth/index.md
        - Social Providers: 
          - howto/config_social/index.md
          - Discord Setup: howto/config_social/discord_oauth.md
          - GitHub Setup: howto/config_social/github_oauth.md
          - Google Setup: howto/config_social/google_oauth.md
          - Twitch Setup: howto/config_social/twitch_oauth.md
          - Twitter Setup: howto/config_social/twitter_oauth.md
        - Custom IAM Providers:
          - howto/config_idm/index.md
          - Cognito: howto/config_idm/cognito_oauth.md
      - Integrate App: 
        - howto/integrate_auth/index.md
        - Vanilla JS App: howto/integrate_auth/integrate_wallet.md
        - React App: 
          - howto/integrate_auth/react/index.md
          - React/NextJS App: howto/integrate_auth/integrate_wallet_react.md
          - Wagmi App: howto/integrate_auth/integrate_wagmi.md
          - RainbowKit App: howto/integrate_auth/integrate_rainbow.md
        - Vue dApp: howto/integrate_auth/integrate_wallet_vue.md
      - Onboard Users: 
        - howto/onboard_users/index.md
        - Plug and Play Login UI: howto/onboard_users/wallet_plugnplay.md
        - Custom Login UI:
          - Build Passwordless Auth: howto/onboard_users/wallet_pwdless_login.md
          - Build Social Auth: 
            - howto/onboard_users/build_social/index.md
            - Discord: howto/onboard_users/build_social/wallet_discord_oauth.md
            - GitHub: howto/onboard_users/build_social/wallet_github_oauth.md
            - Google: howto/onboard_users/build_social/wallet_google_oauth.md
            - Twitch: howto/onboard_users/build_social/wallet_twitch_oauth.md
            - Twitter: howto/onboard_users/build_social/wallet_twitter_oauth.md
          - Build Custom Auth:
            - howto/plug_idm/index.md
            - Cognito: howto/plug_idm/wallet_cognito_oauth.md           
      - Enable Arcana Wallet:
        - howto/arcana_wallet/index.md
        - Configure Wallet Visibility: howto/arcana_wallet/config_walletvisibility.md
        - Web3 Wallet Ops:
          - howto/arcana_wallet/web3ops/index.md
          - Add / Switch Network: howto/arcana_wallet/wallet_add_switch_ntwk.md
          - Check Wallet Balance: howto/arcana_wallet/wallet_balance.md
          - Send Tokens: howto/arcana_wallet/wallet_send.md
          - Sign Transactions: howto/arcana_wallet/wallet_sign.md
          - Show Wallet: howto/arcana_wallet/wallet_show.md
          - Watch Assets: howto/arcana_wallet/wallet_watchasset.md
      - Deploy App: howto/deploy_app.md
  - Tutorials: 
      - tutorials/index.md
      - Code Samples: 
        - tutorials/code-samples/index.md
        - HTML/JS Example: tutorials/code-samples/vanilla-html-js-sample.md
        - React Example: tutorials/code-samples/react-code-sample.md
        - NextJS Example: tutorials/code-samples/nextjs-code-sample.md
        - Vue Example: https://github.com/arcana-network/auth-sample-integration-new
      - Videos: 
        - tutorials/videos/index.md
        - Get Started: tutorials/videos/get-started.md
  - User Guides:
      - user-guides/index.md
      - Using Arcana Dashboard: db/config-dApp-with-db.md
      - Using Arcana Wallet: 
        - user-guides/wallet-ui/index.md
        - Basic Wallet Operations: howto/use-wallet-ui.md
        - Export Private Key: howto/use-wallet-to-export-keys.md
        - Manage Tokens: howto/use-wallet-to-manage-tokens.md
        - Manage NFTs: howto/wallet_manage_nft.md
      - MFA Setup User Guide: user-guides/mfa/mfa-ug.md
  - Developer Resources:
    - Handling Auth Errors: web-sdk/auth-error-msg.md
    - FAQ:
      - faq/index.md
      - General: faq/faq-gen.md
      - Dashboard: faq/faq-db.md
      - Auth SDK: faq/faq-auth.md
      - Validator Nodes: faq/faq-validator.md
    - Troubleshooting Guide: troubleshooting.md
    - Release Notes: 
      - relnotes/index.md
    - Archives: 
        - archives/index.md
        - Migration Guides:
          - migration/archives/index.md
          - v1.0.2 -> v1.0.3: migration/main-auth-v1.0.3-migration.md
          - v1.0.1 -> v1.0.2: migration/main-auth-v1.0.2-migration.md
          - v1.0.0 -> v1.0.1: migration/main-auth-v1.0.1-migration.md
          - v0.3.0 -> v1.0.0: migration/main-auth-v1.0.0-migration.md
          - v0.2.x -> v0.3.0: migration/beta-auth-v0.3.0-migration.md
        - Release Notes:
          - relnotes/archives/index.md
          - Auth 1.0.3 : relnotes/rn-main-auth-v1.0.3.md
          - Auth 1.0.2 : relnotes/rn-main-auth-v1.0.2.md
          - Auth 1.0.1 : relnotes/rn-main-auth-v1.0.1.md
          - Auth 1.0.0 (Mainnet): relnotes/rn-main-auth-v1.0.0.md
          - Auth 0.3.0 (Testnet): relnotes/rn-beta-auth-v0.3.0.md
    - Changelog:
      - changelog/index.md
      - Auth SDK Changelog: https://github.com/arcana-network/auth/releases/tag/v1.0.3
      - Dashboard Changelog: https://github.com/arcana-network/developer-dashboard/releases/tag/v1.0.4
    - Blockchain Integrations:
      - EVM Chains:
        - Shardeum: 
          - integrations/shardeum/index.md
          - Developer's Guide: integrations/shardeum/integrate-shardeum.md
          - Using Wallet UI: integrations/shardeum/wallet-config-shardeum.md
  - Reference:
      - reference/index.md
      - State of the Arcana Auth: state-of-the-arcana-auth.md
      - Auth SDK Usage Guide: web-sdk/auth-usage-guide.md
      - SDK Reference Guide: 'https://authsdk-ref-guide.netlify.app/'
      - Technical Whitepaper: https://www.notion.so/Arcana-Technical-Docs-a1d7fd0d2970452586c693e4fee14d08
  - Arcana Academy:
      - an-academy/index.md
      - About Arcana Auth:
        - about-auth/index.md
        - What is Arcana Auth?: what-is-arcana-auth.md
        - Why Arcana Auth?: why-arcana-auth.md
        - How to Use Auth?: how-to-use-auth.md
        - Web3 Auth Use Cases: use-cases.md
      - Architecture: auth-architecture.md
      - Smart Contracts:
        - concepts/ansmartc/index.md
        - Overview: concepts/ansmartc/an_smart_contracts.md
        - Types of Contracts: concepts/ansmartc/an_smartc_types.md
        - Deployed Contracts: concepts/ansmartc/an_smartc_deployed.md
        - Contract Details: concepts/ansmartc/an_smartc_details.md
        - Contract Flows: concepts/ansmartc/an_smartc_flows.md
        - Upgradeable Contracts: concepts/ansmartc/an_smartc_upgrades.md
      - Concepts: 
        - concepts/index.md
        - Aggregate Login: concepts/authtype/aggregatelogin.md
        - Arcana Web3 Wallet: 
          - concepts/anwallet/index.md
          - Overview: concepts/anwallet/arcanawallet_oview.md
          - Wallet Features: concepts/anwallet/walletfeatures.md
          - Wallet Visibility: concepts/anwallet/walletuimodes.md
          - Switching Networks: concepts/anwallet/walletntwkswitchmode.md
          - Using Web3 Wallet vs. Key: concepts/anwallet/walletorkey.md
          - Sign Transaction Messages: concepts/anwallet/walletstgsigntx.md
        - Auth SDK: concepts/authsdk.md
        - Authentication: concepts/authtype/arcanaauth.md
        - Auth Providers:
          - concepts/authtype/index.md
          - Social Providers: concepts/authtype/socialauth.md
          - Custom IAM Providers: concepts/authtype/customauth.md
          - Passwordless: concepts/authtype/pwdless.md
        - Usage & Billing: concepts/billing.md
        - Dashboard: concepts/dashboard.md
        - DKG:
          - concepts/dkg/index.md
          - What is DKG?: concepts/dkg.md
          - How does DKG work?: concepts/how_dkg_works.md
        - Gateway: concepts/gateway_nodes.md
        - MFA: concepts/mfa.md
        - Plug and Play Auth: concepts/plugnplayauth.md
        - Private Key: concepts/privatekey.md
        - Shared Key Space: concepts/sharedkeys.md
        - Usage Metrics: concepts/usage_metrics.md
        - Validator Nodes: concepts/validator_nodes.md
      - Usage Flows: 
        - user-flows/index.md
        - User Auth and DKG: user-flows/user-auth-and-dkg.md
      - New to Web3:  an-academy/new-to-web3.md
  - DKG Validators: 
    - onboard-validators.md
  - Audit Reports: 
    - audit/index.md
    - Arcana Smart Contracts: https://github.com/arcana-network/audit-reports/blob/main/REP-final-20221228T082421Z.pdf
    - Arcana ADKG: https://github.com/arcana-network/audit-reports/blob/main/REP-final-20230228T054948Z.pdf
  - Contact Us: 
    - support.md

extra:
  arcana:
    company_name: Arcana
    product_name: Arcana Auth
    sdk_name: Arcana Auth SDK
    dashboard_name: Arcana Developer Dashboard
    wallet_name: Arcana wallet
    app_address: Client ID
    latest_version: 'v1.0.3'
    auth_sdk_pkg_name: auth
    react_sdk_pkg_name: auth-react
    wagmi_sdk_pkg_name: auth-wagmi
  homepage: https://arcana.network
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/arcananetwork
    - icon: fontawesome/brands/telegram
      link: https://t.me/ArcanaNetwork
    - icon: fontawesome/brands/discord
      link: https://discord.gg/9vrxze3JRR
    - icon: material/chat
      link: https://github.com/orgs/arcana-network/discussions
    #- icon: material/chat
    #  link: https://forum.arcana.network/
  generator: false
  analytics:
    provider: google
    property: !ENV [GOOGLE_ANALYTICS_ID, default='XXXXXXXXXX']
    feedback:
      title: <hr>Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! 

copyright: Copyright &copy; 2022 - 2023 Arcana Network
repo_url: https://github.com/arcana-network/
edit_uri: ""

theme:
  name: material
  logo: img/arcana-logo-white.svg
  icon:
    repo: fontawesome/brands/github
  favicon: img/an-favicon.png
  custom_dir: docs/overrides
  features: 
  #  - announce.dismiss
    - header.autohide 
  #  - navigation.path  //Sponsors only
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.sections
    - navigation.footer
  #  - navigation.expand
  #  - navigation.tabs
  #  - navigation.tabs.sticky
  #  - navigation.prune
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  # - toc.integrate 
    - content.tabs.link
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to Dark Mode

    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to Light Mode

extra_css:
  - stylesheets/custom.css

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - def_list
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.snippets:
      auto_append:
        - ./includes/git_info.md
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - tables

extra_javascript:
  - javascripts/mathjax.js
  # - javascripts/andropdown.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
plugins:
  - macros:
      include_dir: ./includes
  - search:
      lang: en
  - open-in-new-tab
  - alias
  - meta-descriptions:
      export_csv: true
      quiet: false
      enable_checks: false
      min_length: 50
      max_length: 160
  - redirects:
      redirect_maps:
        'introduction.md': 'introducing-arcana-auth.md'
        'walletsdk/wallet_qs.md': 'auth-quick-start.md'
        'walletsdk/wallet_err.md': 'web-sdk/auth-error-msg.md'
        'walletsdk/wallet_usage.md': 'web-sdk/auth-usage-guide.md'
        'an_academy/new_web3_dev.md': 'an-academy/new-to-web3.md'
        'state_of_the_ntwk.md': 'state-of-the-arcana-auth.md'
        'howdoiuse.md': 'how-to-use-auth.md'
        'howitworks.md': 'auth-architecture.md'
        'use_cases.md': 'use-cases.md'
        'validator_intro.md': 'onboard-validators.md'
        'whatisan.md': 'what-is-arcana-auth.md'
        'whyan.md': 'why-arcana-auth.md'
        'understanding_an/index.md': 'about-auth/index.md'
        'migration/index.md': 'migration/archives/index.md'
        'relnotes/rn_main_auth_v1.0.3.md': 'relnotes/rn-main-auth-v1.0.3.md'
        'migration/main_auth_v1.0.3_migration.md': 'migration/main-auth-v1.0.3-migration.md'
        'user_flows/index.md': 'user-flows/index.md'
        'user_flows/user_auth_and_dkg.md': 'user-flows/user-auth-and-dkg.md'
        'user_guides/index.md': 'user-guides/index.md'
        'user_guides/wallet_ui/index.md': 'user-guides/wallet-ui/index.md'
        'user_guides/mfa/mfa_ug.md': 'user-guides/mfa/mfa-ug.md'
        'db/config_dApp_with_db.md': 'db/config-dApp-with-db.md'
        'integrations/shardeum/integrate_shardeum.md': 'integrations/shardeum/integrate-shardeum.md'
        'integrations/shardeum/wallet_config_shardeum.md': 'integrations/shardeum/wallet-config-shardeum.md'
        'tutorials/code_samples/index.md': 'tutorials/code-samples/index.md'
        'tutorials/code_samples/vanilla_html_js_sample.md': 'tutorials/code-samples/vanilla-html-js-sample.md'
        'tutorials/code_samples/react_code_sample.md': tutorials/code-samples/react-code-sample.md
        'tutorials/code_samples/nextjs_code_sample.md': tutorials/code-samples/nextjs-code-sample.md
        'tutorials/videos/an_academy.md': 'tutorials/videos/get-started.md'
        'howto/wallet_ui.md': 'howto/use-wallet-ui.md'
        'howto/wallet_manage_tokens.md': 'howto/use-wallet-to-manage-tokens.md'
        'howto/wallet_exkey.md': 'howto/use-wallet-to-export-keys.md'
  - git-authors:
      show_email_address: false
  - git-revision-date-localized
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: fade
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - an-screenshots-noeffects
      auto_caption: true
      caption_position: bottom
