extends: existence
message: "Paragraph should end with a period."
level: error
scope: paragraph
raw:
  # Match any paragraph that:
  # 1. Isn't between front matter markers (---)
  # 2. Isn't an admonition line (starting with !!! or ???)
  # 3. Isn't a list item (starting with - or *)
  # 4. Isn't a single-line template expression ({...})
  # 5. Isn't a tab heading (starting with ===)
  # 6. Isn't just whitespace
  # 7. Doesn't end with ==}, ]], { .something}, :, or >
  # 8. Requires period even if paragraph contains {{...}} variables
  - '^(?!(?:---|[!?]{3}|===|>|\s*[-\*]|\s*$|{\s*.*}\s*$|.*==}\s*$|.*\{\s*\.[^}]+\}\s*$))[^{].*[^.!?\]>:](?!\])\s*$'
