name: Arcana Documentation Issue Report
description: File an issue/bug report for Arcana Documetation
title: "[Docs Issue]: Cannot find how to do xyz with Arcana SDKs."
labels: ["docs", "bug", "triage"]
assignees:
  - shaloo
body:
  - type: markdown
    attributes:
      value: |

        :wave:  **Hey, there!**
        *Thank you for sharing your feedback.*
        Help us prioritize and attend to your issue right away by providing more details, see below.
  - type: checkboxes
    id: issue-checklist
    attributes:
      label: Issue Checklist
      description: Make sure you are reporting a documentation issue with a screenshot.
      options:
        - label: Is this something you can **debug and fix** in the docs? Send a pull request! We will review and merge, if appropriate.
          required: false
        - label: Did you try using the Arcabot on the bottom right to find what you were looking for in the documentation?
          required: false
  - type: markdown
    attributes:
      value: "## Create GitHub Issue for Arcana Documentation"
  - type: markdown
    attributes:
      value: |

        List the issue along with the screenshot.

        If the info is missing we'll add the 'Needs more information' label and prioritize it only when there is enough information provided.
  - type: textarea
    id: ref-page
    attributes:
      label: Reference Page Link
      description: Please provide a link to the reference page and describe the documentation bug.
      placeholder: Tell us what you see!
      value: "Can't find information regarding... or some section is missing a detail or some incorrect information."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Reader Expectation
      description: Tell us, what did you expect to read or find in Arcana Network documentation?
      placeholder: Was the information missing or confusing or unclear?
      value: "On the page it does not state that..., etc."
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        * Provide screenshots where appropriate
  - type: textarea
    id: browser-env
    attributes:
      label: Documentation Browsing Environment
      description: Describe your browser environment.
      placeholder: Chrome / Safari / Other
      value: |
        * Which browser / version you were using to access the Arcana Network documentation?
        * Are you using Mac, Linux or Windows desktop platform?
        * Are you using iOS / Android / other mobile platform?
    validations:
      required: false
