# This is a basic workflow to help you get started with Actions

name: Vale Lint Check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events on any branch
  push:
  pull_request:
    branches: '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 
    branches: '*'
   

jobs:
  vale-lint:
    runs-on: ubuntu-latest
    steps:
        
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Add Vale Config
        run: |
          ln -s /home/runner/work/auth-mkdocs/auth-mkdocs/config  /home/runner/work/auth-mkdocs/auth-mkdocs/vale/styles/config 

      - uses: errata-ai/vale-action@v2.1.1              

      - name: Check Vale version
        run: |
          which vale
          vale --version

      - name: Run Vale Checks
        run: |
          ./scripts/run_vale_tests.sh

