# This is a basic workflow to help you get started with Actions

name: Vale Lint Check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events on any branch
  push:
  pull_request:
    branches: '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  vale-lint:
    runs-on: ubuntu-latest
    steps:
        
      - name: Checkout Repository
        uses: actions/checkout@v4
              
      - name: Set Up Vale
        run: |
          curl -fsSL https://github.com/errata-ai/vale/releases/latest/download/vale-linux.tar.gz | tar xz
          sudo mv vale /usr/local/bin/
          vale --version

      - name: Run Vale Checks
        run: |
          ./scripts/run_vale_tests.sh

