# This is a basic workflow to help you get started with Actions

name: Vale Lint Check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events on any branch
  push:
  pull_request:
    branches: '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 
    branches: '*'
   

jobs:
  vale-lint:
    runs-on: ubuntu-latest
    steps:
        
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@v2.1.1              
        with:
          files: '["docs/**/*.md", "includes/**/*.md"]'
          fail_on_error: true
